#!/bin/bash
#
# Creates the file .update_timestamp if the current commit has changed an XML
# database file.  This is then used by post-commit to update the database
# timestamp.  You install these scripts by copying them into .git/hooks.  Watch
# out for existing hooks that you may overwrite there.

if [[ -n $(git diff --cached data/db/*.xml) ]]
then
    touch .update_timestamp
fi
exit 0
