/* config file for lensfun library 
   generated by CMake
*/

#define CONF_PACKAGE "lensfun"
#define CONF_VERSION "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_MICRO@.@VERSION_BUGFIX@"

#cmakedefine PLATFORM_WINDOWS

#cmakedefine CMAKE_COMPILER_IS_GNUCC 
#ifdef CMAKE_COMPILER_IS_GNUCC 
#define CONF_COMPILER_GCC 1 
#endif

#ifndef PLATFORM_WINDOWS
//fix path to data works only on *nix systems
//on windows that data dir is relocatable
#define CONF_DATADIR "${CMAKE_INSTALL_PREFIX}/${DATADIR}"
#endif

// add a macro to know we're compiling lensfun, not a client library
#define CONF_LENSFUN_INTERNAL

#cmakedefine VECTORIZATION_SSE
#cmakedefine VECTORIZATION_SSE2

#cmakedefine HAVE_ENDIAN_H

#ifdef _MSC_VER
#define _USE_MATH_DEFINES
#endif
