image: Visual Studio 2017
configuration:
  - Release
  - Debug
cache:
  - c:\Tools\vcpkg\installed
  - c:\Tools\msys64\var\cache\pacman
environment:
  matrix:
    - generator: Visual Studio 15 2017 Win64
    - generator: Visual Studio 14 2015 Win64
    - generator: Unix Makefiles
    - generator: Unix Makefiles
      cmake_eflags: -DBUILD_STATIC=ON
matrix:
  fast_finish: true
install:
  - cmd: if "%bits%"=="32" (set bitness=i) else (set bitness=x)
  - cmd: if "%generator%"=="Unix Makefiles" set "PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%Path%"
  - cmd: if "%generator%"=="Unix Makefiles" bash -lc exit >nul
  - cmd: if "%generator%"=="Unix Makefiles" pacman -Sqyyuu --noconfirm --ask=20
  - cmd: if "%generator%"=="Unix Makefiles" pacman -Squ --noconfirm --ask=20
  - cmd: if "%generator%"=="Unix Makefiles" bash -lc 'pacboy -Sq --noconfirm --ask=20 cmake:%bitness% libpng:%bitness% libxml2:%bitness% toolchain:%bitness% glib2:%bitness%
  - cmd: if not "%generator%"=="Unix Makefiles" vcpkg install glib:x64-windows
  - cmd: if not "%generator%"=="Unix Makefiles" set "cmake_eflags=-DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake %cmake_eflags%"
  - cmd: if "%generator:~0,6%"=="Visual" set "cmake_build_flags=/logger:^"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll^" %cmake_build_flags%"
  - cmd: mkdir build
  - cmd: cd build
  - ps: cmake .. -G"$env:generator" -DCMAKE_BUILD_TYPE=%CONFIGURATION% $env:cmake_eflags
# /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build_script:
  - cmd: cmake --build . --config %CONFIGURATION% -- %cmake_build_flags%
  - cmd: cmake --build . --target install --config %CONFIGURATION%


#artifacts:

#deploy:
#  - provider: GitHub
#    artifact: $(APPVEYOR_PROJECT_NAME)
#    auth_token:
#      secure: 'sf0pQXlPI+X6LoAR8QUJB74jjzNxcLGOXI3H0nbxJq8llvGPG/TAUd87hq5iHZXo'
#    prerelease: true
#    on:
#      appveyor_repo_tag: true
