image: Visual Studio 2017
configuration:
  - Release
  - Debug
cache:
  - c:\Tools\vcpkg\installed
environment:
  matrix:
    - generator: Unix Makefiles
    - generator: Unix Makefiles
      cmake_eflags: -DBUILD_STATIC=ON
    - generator: Visual Studio 15 2017 Win64
    - generator: Visual Studio 14 2015 Win64
matrix:
  fast_finish: true
install:
  - cmd: if "%bits%"=="32" (set bitness=i) else (set bitness=x)
  - cmd: if "%generator%"=="Unix Makefiles" set "PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%Path%"
  - cmd: if "%generator%"=="Unix Makefiles" bash -lc exit >nul
  - cmd: if "%generator%"=="Unix Makefiles" pacman -Syyuu --noconfirm --ask=20
  - cmd: if "%generator%"=="Unix Makefiles" pacman -Su --noconfirm --ask=20
  - cmd: if "%generator%"=="Unix Makefiles" bash -lc 'pacboy -S --noconfirm --ask=20 cmake:%bitness% libpng:%bitness% libxml2:%bitness% toolchain:%bitness% glib2:%bitness%
  - cmd: if not "%generator%"=="Unix Makefiles" vcpkg install glib:x64-windows
  - cmd: if not "%generator%"=="Unix Makefiles" set "cmake_eflags=-DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake %cmake_eflags%"
  - cmd: mkdir build
  - cmd: cd build
  - ps: cmake .. -G"$env:generator" $env:cmake_eflags

build_script:
  - cmake --build . --config debug
  - cmake --build . --target install --config release


#artifacts:

#deploy:
#  - provider: GitHub
#    artifact: $(APPVEYOR_PROJECT_NAME)
#    auth_token:
#      secure: 'sf0pQXlPI+X6LoAR8QUJB74jjzNxcLGOXI3H0nbxJq8llvGPG/TAUd87hq5iHZXo'
#    prerelease: true
#    on:
#      appveyor_repo_tag: true
